# Generated by Django 4.1 on 2024-08-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_card_penalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='time_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
