# Generated by Django 4.2 on 2024-09-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_hint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['points']},
        ),
    ]
