# Generated by Django 4.2 on 2024-09-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='task',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
