# Generated by Django 4.2 on 2024-09-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_task_options_task_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='my_order',
            new_name='order',
        ),
    ]
