# Generated by Django 4.2 on 2024-09-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_task_options_rename_my_order_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='solved_questions',
            field=models.IntegerField(default=0),
        ),
    ]
