# Generated by Django 4.2 on 2024-09-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_card_solved_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='solved_questions',
        ),
    ]
